services:
  postgres:
    image: postgres:latest
    container_name: MyFriendsShowList
    environment:
      POSTGRES_DB: MyFriendsShowList
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: