CREATE TABLE media_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    release_date TIMESTAMP WITHOUT TIME ZONE,
    media_type   VARCHAR(255),
    CONSTRAINT pk_mediaentity PRIMARY KEY (id)
);
